apiVersion: v1
kind: Service
metadata:
  name: apex-backend-service
  namespace: apex-solutions
  labels:
    app: apex-backend
spec:
  type: ClusterIP
  selector:
    app: apex-backend
  ports:
    - port: 3000
      targetPort: 3000
      name: http
      protocol: TCP
